from .main_window import MainWindow
from .login_window import LoginWindow
from .signup_dialog import SignupDialog
from .forgot_password_dialog import ForgotPasswordDialog
from .dashboard_page import DashboardPage
from .my_classes_page import MyClassesPage
from .attendance_page import AttendancePage
from .schedule_page import SchedulePage
from .resources_page import ResourcesPage
from .settings_page import SettingsPage
